# Generated by Django 2.2.12 on 2020-08-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=120, verbose_name='详细地址')),
                ('area', models.CharField(max_length=30, verbose_name='所属地区')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50, verbose_name='车型')),
                ('brand', models.CharField(max_length=20, verbose_name='品牌')),
                ('car_licence', models.CharField(max_length=15, verbose_name='车牌')),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='新车购车价')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='二手车售价')),
                ('mileage', models.CharField(max_length=20, verbose_name='公里数')),
                ('purchase_time', models.CharField(max_length=20, verbose_name='购车时间')),
                ('emissions', models.CharField(max_length=10, verbose_name='排放')),
                ('is_checked', models.BooleanField(default=0, verbose_name='审核情况')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否上架')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.User')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100, verbose_name='照片名')),
                ('img_path', models.CharField(max_length=200, verbose_name='存储路径')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardb.Cars')),
            ],
            options={
                'db_table': 'carimage',
            },
        ),
    ]
