# Generated by Django 2.2.12 on 2020-08-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_first_imgpath',
            field=models.CharField(default=None, max_length=300, verbose_name='首页汽车图片链接'),
        ),
    ]
