# Generated by Django 2.2.12 on 2020-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_cars_car_first_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='origin_price',
            field=models.CharField(max_length=30, verbose_name='新车购车价'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='selling_price',
            field=models.CharField(max_length=30, verbose_name='二手车售价'),
        ),
    ]
